<?php
$hasImg = false;
$hasQty = false;
$defaultImg = $di->config->get('cart.img_cart_default_path');
foreach ($cart->getItems() as $item) {
    $hasImg = $hasImg || $item->tryLoadProduct()->img_cart_path || $defaultImg;
    $hasQty = $hasQty || $item->qty > 1 || $item->variable_qty;
}
$paysystems = Am_Di::getInstance()->paysystemList->getAllPublic();

?>
<style>
    .am-basket-img {
        overflow: hidden;
        width:
            <?php echo $di->config->get('cart.img_cart_width', 50); ?>
            px;
        height:
            <?php echo $di->config->get('cart.img_cart_height', 50); ?>
            px;
    }
</style>
<?php $colspan = $hasQty ? 3 : 1; ?>

<ul class="basket-list" id="basket">
    <div class="basket-flex">
        <div class="checkout-top-container">
            <div class="basket-header">
                <span class="basket-title"><?php __e('Order Summary') ?></span>
            </div>
            <div class="continue-shopping-flex">

                    <form method="post" action="<?php echo $this->url('cart/checkout') ?>">
                        <?php echo Am_Html::renderArrayAsInputHiddens($_REQUEST); ?>
                        <div class="am-cart-checkout-buttons">
                            <input type="button" class="am-cart-checkout-buttons-update" id="edit-cart-btn"
                                value="<?php __e('Edit Your Cart') ?>"
                                onclick="window.location.href = '<?php echo $this->url('cart/view-basket') ?>'; toggleButtons()" />
                            <input type="hidden" name='a' value='checkout'>
                        </div>
                    </form>

                    <div class="am-cart-checkout-buttons" id="checkout-buttons">
                        <input type="submit" class="am-cart-checkout-buttons-checkout" name="do-checkout"
                            value="<?php __e('Checkout') ?>" />
                        <input type="hidden" name="b" value="<?php p($b) ?>" />
                    </div>
            </div>
        </div>
        <div class="whatif">
            <?php foreach ($cart->getItems() as $item): ?>
                <li class="basket-item">
                    <div class="basket-item-details">
                        <div class="basket-container-img">
                            <?php if ($hasImg): ?>
                                <div class="basket-item-img">
                                    <?php
                                    if ($item->tryLoadProduct()->img_cart_path)
                                        $img_url = $item->tryLoadProduct()->img_cart_path;
                                    else
                                        $img_url = $defaultImg;
                                    $img_url = $this->url('data/public/' . $img_url);
                                    ?>
                                    <?php if ($img_url): ?>
                                        <img src="<?php echo $img_url; ?>" alt="Product Image" />
                                    <?php endif ?>
                                </div>
                            <?php endif; ?>
                        </div>
                        <div class="container-flex">
                            <div class="basket-item-title"><strong><?php p($item->item_title) ?></strong></div>
                            <div class="basket-item-desc"><?php p($item->item_description) ?></div>
                            <div class="container-row-flex-checkout">
                                <span class="basket-item-price"><?php p($cart->getCurrency($item->first_price)) ?></span>
                                <?php if ($hasQty): ?>
                                    <span class="basket-item-qty">
                                        <?php if ($item->is_countable && $item->variable_qty && $isBasket && !$cart->isStick($item)): ?>
                                            <div class="basket-qty-controls">
                                                <button class="basket-qty-minus">&minus;</button>
                                                <?php echo $this->formText("qty[$item->item_id]", $item->qty, ['size' => 1, 'class' => 'basket-qty-val']) ?>
                                                <button class="basket-qty-plus">&plus;</button>
                                            </div>
                                        <?php else: ?>
                                            <?php p($item->qty) ?>
                                        <?php endif; ?>
                                    </span>
                                    <span class="basket-item-total"><?php p($cart->getCurrency($item->first_total)) ?></span>
                                <?php endif; ?>
                            </div>
                        </div>
                        <?php if ($isBasket): ?>
                            <div class="am-basket-delete"><?php if (!$cart->isStick($item)): ?><a href="javascript:;"
                                        title="<?php __e('Delete') ?>"><input type="checkbox"
                                            name="d[<?php echo $item->item_id ?>-<?php echo $item->item_type ?>]"
                                            value="1">&#10005;</a><?php endif ?></div>
                        <?php endif; ?>
                    </div>
                </li>
            <?php endforeach ?>
        </div>
        <li class="basket-divider">

        </li>
        <form method="post" action="<?php echo $this->url('cart/checkout') ?>">
            <?php echo Am_Html::renderArrayAsInputHiddens($_REQUEST); ?>
            <div class="am-cart-checkout-buttons">
                <input type="button" class="am-cart-checkout-buttons-update" value="<?php __e('Edit Your Cart') ?>"
                    onclick="window.location.href = '<?php echo $this->url('cart/view-basket') ?>'" />
                <input type="hidden" name='a' value='checkout'>
            </div>
        </form>
        <div class="totals-container">
            <li class="basket-totals basket-subtotal">
                <span class="basket-label"><?php __e('Subtotal') ?></span>
                <span class="basket-amount"><?php p($cart->getCurrency($cart->getInvoice()->first_subtotal)) ?></span>
            </li>

            <li class="basket-totals basket-discount">
                <span class="basket-label"><?php __e('Discount') ?></span>
                <span class="basket-amount"><?php p($cart->getCurrency($cart->getInvoice()->first_discount)) ?></span>
            </li>

            <li class="basket-totals basket-shipping">
                <span class="basket-label"><?php __e('Shipping') ?></span>
                <span class="basket-amount"><?php p($cart->getCurrency($cart->getInvoice()->first_shipping)) ?></span>
            </li>
            <li class="basket-totals basket-tax">
                <span class="basket-label"><?php __e('Tax') ?></span>
                <span class="basket-amount"><?php p($cart->getCurrency($cart->getInvoice()->first_tax)) ?></span>
            </li>

            <li class="basket-totals basket-terms">
                <span class="basket-terms-label"><?php __e('Terms') ?>:</span>
                <span class="basket-terms-content"><?php echo ___($cart->getInvoice()->getTerms()) ?></span>
            </li>
            <li class="basket-totals basket-grandtotal">
                <span class="basket-label"><?php __e('Total') ?></span>
                <span class="basket-amount"><?php p($cart->getCurrency($cart->getInvoice()->first_total)) ?></span>
            </li>

            <div class="am-cart-checkout-buttons">
                <input type="submit" class="am-cart-checkout-buttons-checkout" name="do-checkout"
                    value="<?php __e('Checkout') ?>" />
                <input type="hidden" name="b" value="<?php p($b) ?>" />
            </div>
        </div>
    </div>
    <div class="basket-flexx">
        <span class="basket-title"><?php __e('Payment Details') ?></span>
        <h2 class="payment-head-title">
            <?php
            if (count($paysystems) > 1):
                __e('Select Payment Method');
            elseif (count($paysystems) == 1):
                __e('Payment Method');
            endif;

            ?>
        </h2>

        <li class="basket-divider"></li>
        <div id="choose-paysys-wrapper">
            <div id="ps-errors-container"></div>
            <div class="am-cart-checkout-paysys">
                <?php foreach ($paysystems as $ps): ?>
                    <div id="am-cart-checkout-paysys-<?= $ps->getId() ?>" class="am-cart-checkout-paysys-item <?php if (!empty($cart->getInvoice()->paysys_id) && ($cart->getInvoice()->paysys_id == $ps->getId()))
                          echo 'active'; ?>" data-paysys_id='<?php p($ps->getId()); ?>'>
                        <label for="ps-<?php p($ps->getId()) ?>">
                            <input type="radio" name="paysys_id" value="<?= $ps->getId() ?>" <?php if (!empty($cart->getInvoice()->paysys_id) && ($cart->getInvoice()->paysys_id == $ps->getId()))
                                  echo 'checked'; ?>>
                            <div>
                                <span class='am-cart-checkout-paysys-item-title'><strong><?php echo $ps->getTitle() ?>
                                    </strong><?php echo $ps->getDescription() ?></span>
                            </div>
                        </label>
                    </div>
                <?php endforeach ?>
            </div>
        </div>

        <li class="basket-totals basket-grandtotal">
            <span class="basket-label"><?php __e('Total') ?></span>
            <span class="basket-amount"><?php p($cart->getCurrency($cart->getInvoice()->first_total)) ?></span>
        </li>
        <form method="post" action="<?php echo $this->url('cart/checkout') ?>">
            <?php echo Am_Html::renderArrayAsInputHiddens($_REQUEST); ?>
            <div class="am-cart-checkout-buttons">
                <?php if (isset($choosePaysys)): ?>
                    <input type="hidden" name="choose-paysys" value="1" />
                <?php endif; ?>
                <input type="submit" class="am-cart-checkout-buttons-checkout"
                    value="<?php __e('Proceed to Checkout') ?>" />
            </div>
        </form>
    </div>
</ul>

<script type="text/javascript">
    jQuery('.am-basket-delete > a').click(function () {
        jQuery(this).find('input').attr('checked', 'checked');
        jQuery(this).closest('form').find('.am-cart-checkout-buttons-update').click();
    });
</script>