<?php
$hasImg = false;
$hasQty = false;
$defaultImg = $di->config->get('cart.img_cart_default_path');
foreach ($cart->getItems() as $item) {
    $hasImg = $hasImg || $item->tryLoadProduct()->img_cart_path || $defaultImg;
    $hasQty = $hasQty || $item->qty > 1 || $item->variable_qty;
}
?>
<style>
    .am-basket-img {
        overflow: hidden;
        width:
            <?php echo $di->config->get('cart.img_cart_width', 50); ?>
            px;
        height:
            <?php echo $di->config->get('cart.img_cart_height', 50); ?>
            px;
    }
</style>
<?php $colspan = $hasQty ? 3 : 1; ?>
<ul class="basket-list" id="basket">
    <li class="basket-header">
        <span class="basket-item-title"><?php __e('Order Summary') ?></span>
        <span class="basket-item-price"><?php __e('Price') ?></span>
        <?php if ($hasQty): ?>
            <span class="basket-item-qty"><?php __e('Qty') ?></span>
            <span class="basket-item-total"><?php __e('Total') ?></span>
        <?php endif; ?>
    </li>
    <?php foreach ($cart->getItems() as $item): ?>
        <li class="basket-item">
            <div class="basket-item-details">
                <div class="basket-container">
                    <?php if ($isBasket): ?>
                        <div class="basket-item-delete">
                            <?php if (!$cart->isStick($item)): ?>
                                <a href="javascript:;" title="<?php __e('Delete') ?>">
                                    <input type="checkbox" name="d[<?php echo $item->item_id ?>-<?php echo $item->item_type ?>]"
                                        value="1">
                                    &#10005;
                                </a>
                            <?php endif ?>
                        </div>
                    <?php endif; ?>

                    <?php if ($hasImg): ?>
                        <div class="basket-item-img">
                            <?php
                            if ($item->tryLoadProduct()->img_cart_path)
                                $img_url = $item->tryLoadProduct()->img_cart_path;
                            else
                                $img_url = $defaultImg;
                            $img_url = $this->url('data/public/' . $img_url);
                            ?>
                            <?php if ($img_url): ?>
                                <img src="<?php echo $img_url; ?>" alt="Product Image" />
                            <?php endif ?>
                        </div>
                    <?php endif; ?>
                </div>
                <div class="basket-container">
                    <div class="basket-item-title"><strong><?php p($item->item_title) ?></strong></div>
                    <span class="basket-item-price"><?php p($cart->getCurrency($item->first_price)) ?></span>
                    <div class="basket-item-desc"><?php p($item->item_description) ?></div>

                </div>
                <div class="basket-item-options">
                    <?php foreach ($item->getOptions() as $optKey => $opt): ?>
                        <br /><b><i><?php __e($opt['optionLabel']) ?>:</i></b>
                        <i><?php p(is_array($opt['valueLabel']) ? implode(',', $opt['valueLabel']) : $opt['valueLabel']) ?></i>
                        <?php if ($opt['first_price'] || $opt['second_price']): ?>
                            <i style='color: gray;'><?= $opt['first_price'] > 0 ? '+' : '&minus;' ?>
                                <?php
                                $o = new stdclass;
                                $o->first_price = $opt['first_price'];
                                $o->second_price = $opt['second_price'];
                                $o->first_period = $invoice->first_period;
                                $o->second_period = $invoice->second_period;
                                $o->rebill_times = $invoice->rebill_times;
                                $o->currency = $invoice->currency;
                                $t = new Am_TermsText($o);
                                echo $t->getStringForOption();
                                ?>
                            </i>
                        <?php endif ?>
                    <?php endforeach// item->getOptions() ?>
                </div>

            </div>

            <?php if ($hasQty): ?>
                <span class="basket-item-qty">
                    <?php if ($item->is_countable && $item->variable_qty && $isBasket && !$cart->isStick($item)): ?>
                        <div class="basket-qty-controls">
                            <button class="basket-qty-minus">&minus;</button>
                            <?php echo $this->formText("qty[$item->item_id]", $item->qty, ['size' => 1, 'class' => 'basket-qty-val']) ?>
                            <button class="basket-qty-plus">&plus;</button>
                        </div>
                    <?php else: ?>
                        <?php p($item->qty) ?>
                    <?php endif; ?>
                </span>
                <span class="basket-item-total"><?php p($cart->getCurrency($item->first_total)) ?></span>
            <?php endif; ?>
        </li>
    <?php endforeach ?>

    <li class="basket-divider"></li>

    <?php if ($cart->getInvoice()->first_subtotal != $cart->getInvoice()->first_total): ?>
        <li class="basket-totals basket-subtotal">
            <span class="basket-label"><?php __e('Subtotal') ?></span>
            <span class="basket-amount"><?php p($cart->getCurrency($cart->getInvoice()->first_subtotal)) ?></span>
        </li>
    <?php endif; ?>

    <?php if ((float) $cart->getInvoice()->first_discount): ?>
        <li class="basket-totals basket-discount">
            <span class="basket-label"><?php __e('Discount') ?></span>
            <span class="basket-amount"><?php p($cart->getCurrency($cart->getInvoice()->first_discount)) ?></span>
        </li>
    <?php endif; ?>

    <?php if ((float) $cart->getInvoice()->first_shipping): ?>
        <li class="basket-totals basket-shipping">
            <span class="basket-label"><?php __e('Shipping') ?></span>
            <span class="basket-amount"><?php p($cart->getCurrency($cart->getInvoice()->first_shipping)) ?></span>
        </li>
    <?php endif; ?>

    <?php if ((float) $cart->getInvoice()->first_tax): ?>
        <li class="basket-totals basket-tax">
            <span class="basket-label"><?php __e('Tax') ?></span>
            <span class="basket-amount"><?php p($cart->getCurrency($cart->getInvoice()->first_tax)) ?></span>
        </li>
    <?php endif; ?>

    <li class="basket-totals basket-grandtotal">
        <span class="basket-label"><?php __e('Total') ?></span>
        <span class="basket-amount"><?php p($cart->getCurrency($cart->getInvoice()->first_total)) ?></span>
    </li>

    <?php if (!empty($cart->getInvoice()->rebill_times)): ?>
        <li class="basket-terms">
            <span class="basket-terms-label"><?php __e('Terms') ?>:</span>
            <span class="basket-terms-content"><?php echo ___($cart->getInvoice()->getTerms()) ?></span>
        </li>
    <?php endif ?>
</ul>
<script type="text/javascript">
    jQuery('.am-basket-delete > a').click(function () {
        jQuery(this).find('input').attr('checked', 'checked');
        jQuery(this).closest('form').find('.am-cart-checkout-buttons-update').click();
    });
</script>