<div class="faq-search-block">
    <h2 class="search-faq-container">Search FAQ</h2>
    <div style="position: relative;">
    <form action="<?php echo $this->url('helpdesk/faq/search') ?>" method="get" id="helpdesk-search">
        <input class="am-helpdesk-faq-q am-el-wide" id="am-helpdesk-faq-q" type="text" name="q" value="" placeholder="<?php __e('Type a keyword to search in FAQ') ?>" style="padding-left: 35px; width: 40%;" />
        <i class="fas fa-search" style="position: absolute; left: 10px; top: 50%; transform: translateY(-50%); color: #888;"></i>
    </form>
</div>    <div id="am-helpdesk-faq-q-result" class="am-helpdesk-faq-q-result">
    </div>
</div>
<?php $this->_scriptReplaced('helpdesk-block-_search-form'); ?>