<div class="sigin-container">
<?php
$body_class = "am-page-signup am-page-signup-$code";
if (empty($title)) $title=___('Sign-up');
else $title=___($title);
$this->setLayout('layout.phtml');
include $this->_script('_error.phtml');
?>
<div class="am-signup">
<?php echo $this->blocks('signup/login/before', "%s", ['record' => $record, 'code' => $code]) ?>
<?php include $this->_script('signup/_login-offer.phtml'); ?>
<?php echo $this->blocks('signup/login/after', "%s", ['record' => $record, 'code' => $code]) ?>
<?php echo $this->blocks('signup/form/before', "%s", ['record' => $record, 'code' => $code]) ?>
<div class="signup-container">
<?php include $this->_script('_form.phtml'); ?>
</div>

<?php echo $this->blocks('signup/form/after', "%s", ['record' => $record, 'code' => $code]) ?>
</div>
<?php include $this->_script('js.country_state.js'); ?>


</div>
